DELETE  http://localhost:8080/events/47
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InByZXplcy5zaWtvcmExMjNAZ21haWwuY29tIiwiZXhwIjoxNzQyOTIxNDMwLCJ1c2VySWQiOjJ9.XrHO5csXezmdstT9tLOESdllV-51Xmr1gdrBl1Crv5k

###

GET http://localhost:8080/events/1

###

GET http://localhost:8080/events

###

POST http://localhost:8080/events
content-type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InByZXplcy5zaWtvcmExMjNAZ21haWwuY29tIiwiZXhwIjoxNzQwNjY5ODA3LCJ1c2VySWQiOjJ9.QZz3luvgopUatmVaXz97SJtJ7w03_JGBtGTjCY-O9_k

{    
	"name" : "Test event",
	"description" : "Test description",
	"location" : "test location",
	"dateTime" : "2025-02-12T15:30:00.000Z"
}

###

PUT http://localhost:8080/events/3
content-type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InByZXplcy5zaWtvcmExMjNAZ21haWwuY29tIiwiZXhwIjoxNzQwNjY5ODA3LCJ1c2VySWQiOjJ9.QZz3luvgopUatmVaXz97SJtJ7w03_JGBtGTjCY-O9_k

{    
	"name" : "Test event updated",
	"description" : "Test descripti   3123213 123 on",
	"location" : "test location",
	"dateTime" : "2025-02-12T15:30:00.000Z"
}
